title: Hello, world! I'm xuanhua
description: > # 这意味着在“baseurl：”之前忽略换行符
  在这里为您的新网站写一个很棒的描述。你可以编辑它
  _config.yml中的行。它将出现在您的文档头元（for
  Google搜索结果）以及您的feed.xml网站说明。
permalink: ':title/'
baseurl: "" # ＃您网站的子路径，例如/ blog
url: "" # 您网站的基本主机名和协议，例如http://example.com
site-twitter: #如果您的网站有推特账号，请在此处输入

# 作者设置
author: David Freeman #添加你的名字
author-img: david-freeman.jpg # 添加您的照片
about-author: 我是一个喜欢思考的人  #补充说明
social-twitter: # ＃添加你的Twitter句柄
social-facebook: # 添加你的Facebook句柄
social-github: xuanhua6 # 添加你的Github句柄
social-linkedin: # 添加你的Linkedin句柄
social-email: xuanhua6@qq.com # 添加您的电子邮件地址

# 跟踪
discus-identifier: mr-brown # 添加你的铁饼标识符

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-slate
